"""3

Revision ID: bf579468d71c
Revises: 4166d3ade2af
Create Date: 2024-05-13 21:34:25.301265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf579468d71c'
down_revision: Union[str, None] = '4166d3ade2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('best_product', sa.Column('message_id', sa.Integer(), nullable=True))
    op.drop_column('best_product', 'price')
    op.drop_column('best_product', 'name')
    op.drop_column('best_product', 'img')
    op.drop_column('best_product', 'discount')
    op.drop_column('best_product', 'last_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('best_product', sa.Column('last_price', sa.DECIMAL(), nullable=False))
    op.add_column('best_product', sa.Column('discount', sa.INTEGER(), nullable=False))
    op.add_column('best_product', sa.Column('img', sa.VARCHAR(length=255), nullable=False))
    op.add_column('best_product', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.add_column('best_product', sa.Column('price', sa.DECIMAL(), nullable=False))
    op.drop_column('best_product', 'message_id')
    # ### end Alembic commands ###
